// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlephHwD724GQs6x93KrDjPC8b1RBqg5M',
    appId: '1:736923818452:web:3396e732877cb52be65e41',
    messagingSenderId: '736923818452',
    projectId: 'servicify-79e8c',
    authDomain: 'servicify-79e8c.firebaseapp.com',
    storageBucket: 'servicify-79e8c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBhkYz3BkwXkj2WmqYtXHAQwOpafdMSgQ',
    appId: '1:736923818452:android:4e5a38bbd73a01ade65e41',
    messagingSenderId: '736923818452',
    projectId: 'servicify-79e8c',
    storageBucket: 'servicify-79e8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjA5zxwtsMdA0aqZPVAEdwOGMSP_793m4',
    appId: '1:736923818452:ios:6df927ab90baa1e4e65e41',
    messagingSenderId: '736923818452',
    projectId: 'servicify-79e8c',
    storageBucket: 'servicify-79e8c.appspot.com',
    iosBundleId: 'com.ralfiz.servicify',
  );
}
